- hosts: localhost
  connection: local
  gather_facts: False
  tasks: 
    - name: Import vpc variables
      include_vars: vars/vpc_setup

    - name: create shekhar vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - debug:
        var: vpcout
    
    - name: create public subnet1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: shekhar-pubsub1
      register: pubsub1_out
      